In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Step1: Load Data 

In [2]:
data = pd.read_csv("diabetes.csv")

In [3]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
data.shape

(768, 9)

In [5]:
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
data.duplicated().sum()

0

# Step2: Separate Input and out features

In [7]:
X = data.drop('Outcome',axis=1)
y = data['Outcome']

# Step3: Train Test Split

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0, test_size=.20)

# Step4: Model Selection
       - Classification problem in hand

# Common Classification Algorithms:
# Logistic Regression:
                A statistical method for predicting the probability of an event occurring. 
# Support Vector Machines (SVM):
                A powerful algorithm that finds the optimal hyperplane to separate data points into different classes. 
# Decision Trees:
                Algorithms that use a tree-like structure to make predictions based on a series of decisions. 
# Random Forest:
                An ensemble method that combines multiple decision trees to improve accuracy. 
# K-Nearest Neighbors (KNN):
                An algorithm that classifies data points based on the majority class of their nearest neighbors. 
# Neural Networks:
                Complex models inspired by the structure of the human brain, capable of learning complex patterns. 

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
logr = LogisticRegression()

# Step5: Model Fit

In [11]:
logr.fit(X_train,y_train)

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
y_pred_train = logr.predict(X_train)
y_train
y_pred_train

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,

In [13]:
count=0
for t,p in zip(y_train,y_pred_train):
   if t==p:
       count+=1
count

474

In [14]:
len(X_train)

614

In [15]:
count/len(X_train)

0.7719869706840391

# STep 6: Model Evaluation

 Accuracy Score
 knn.score(X_test, y_test)
 from sklearn.metrics import accuracy_score
 accuracy_score(y_test, y_pred) Classification Report
 from sklearn.metrics import classification_report
 print(classification_report(y_test, y_pred))
 Confusion Matrix
 from sklearn.metrics import confusion_matrix
 print(confusion_matrix(y_test, y_pred))
 VALIDATING THE MODEL
 The sklearn.metrics module includes score functions, performance metrics and pairwise metrics and 
distance computations.
 Import and print accuracy, recall, precision, and F1 score:
 from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score 
print(accuracy_score(true_labels, guesses)) print(recall_score(true_labels, guesses)) 
print(precision_score(true_labels, guesses)) print(f1_score(true_labels, guesses))

# Accuracy Score

In [16]:
 from sklearn.metrics import accuracy_score
 accuracy_score(y_train, y_pred_train)

0.7719869706840391

# Classification Report

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       393
           1       0.73      0.58      0.65       221

    accuracy                           0.77       614
   macro avg       0.76      0.73      0.74       614
weighted avg       0.77      0.77      0.77       614



# Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred_train))

[[345  48]
 [ 92 129]]


In [19]:
y_pred_test = logr.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred_test))

[[98  9]
 [18 29]]


In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88       107
           1       0.76      0.62      0.68        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154



In [22]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [23]:
data.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [24]:
class_0 = data[data.Outcome == 0].sample(268)

In [25]:
class_1 = data[data.Outcome == 1].sample(268)

In [26]:
new_data = pd.concat([class_0,class_1]).sample(536)

In [27]:
new_data.Outcome.value_counts()

Outcome
0    268
1    268
Name: count, dtype: int64

In [28]:
X = new_data.drop('Outcome',axis=1)
y = new_data['Outcome']

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0, test_size=.20)

In [30]:
logr.fit(X_train,y_train)

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [31]:
y_pred_train = logr.predict(X_train)

In [32]:
from sklearn.metrics import classification_report
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.75      0.77      0.76       215
           1       0.76      0.74      0.75       213

    accuracy                           0.75       428
   macro avg       0.75      0.75      0.75       428
weighted avg       0.75      0.75      0.75       428



In [33]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred_train))

[[165  50]
 [ 55 158]]


In [34]:
y_pred_test = logr.predict(X_test)

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.68      0.83      0.75        53
           1       0.79      0.62      0.69        55

    accuracy                           0.72       108
   macro avg       0.73      0.72      0.72       108
weighted avg       0.73      0.72      0.72       108



In [36]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred_test))

[[44  9]
 [21 34]]
